database:
  user: your_user
  password: your_password
  host: your_host
  port: 5432
  name: your_database
smtp:
  from: "your-email@example.com"
  password: "your-email-password"
  to: "admin@example.com"
  host: "smtp.gmail.com"
  port: "587"